In [1]:
import pandas as pd
import re

# Load the CSV file
df = pd.read_csv("C:/Users/subasini/Downloads/agg_response/agg_response.csv")

# def clean_name(name):
#     # Remove initials and special characters
#     cleaned_name = re.sub(r'[^a-zA-Z\s]', '', name)
#     # Remove extra spaces
#     cleaned_name = re.sub(r'\s+', ' ', cleaned_name)
#     # Remove single character words (initials)
#     cleaned_name = ' '.join(word for word in cleaned_name.split() if len(word) > 1)
#     return cleaned_name.strip()

# # Apply the cleaning function to the 'aggr_full_name' column
# df['ext_full_name'] = df['aggr_full_name'].apply(clean_name)

# # Save the cleaned names to a new CSV file
# df.to_csv('./cleaned_names.csv', index=False)

C:\Users\subasini\AppData\Roaming\Python\Python311\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
import pandas as pd

# Read data from CSV file
# df = pd.read_csv("./cleaned_names.csv")

# Function to split full name into first name and last name
def split_name(full_name):
    parts = full_name.split()
    first_name = parts[0]
    last_name = ' '.join(parts[1:]) if len(parts) > 1 else ''  # Join remaining parts as last name
    return first_name, last_name

# Apply the function to 'aggr_full_name' column and store in separate columns
df['first_name'], df['last_name'] = zip(*df['full_name'].map(split_name))

df['agg_first_name'], df['agg_last_name'] = zip(*df['aggr_full_name'].map(split_name))


# Save DataFrame to a new CSV file
df.to_csv("./new.csv", index=False)

In [3]:
df

,loc_id,loc_name,aggr_order_channel,aggr_full_name,aggr_soundex_score,channel,full_name,magil_soundex_score,maghil_phone,match_score,first_name,last_name,agg_first_name,agg_last_name
0,14d293a8-81c5-40b2-a208-be1c03a93fad,A2B Parsippany,UberEats,Abhishek S.,A120,Maghil,ABHISHEK,A120,-6292439194,Low,ABHISHEK,,Abhishek,S.
1,14d293a8-81c5-40b2-a208-be1c03a93fad,A2B Parsippany,UberEats,Abhishek S.,A120,Maghil,Abhisek,A120,-9736416575,Low,Abhisek,,Abhishek,S.
2,14d293a8-81c5-40b2-a208-be1c03a93fad,A2B Parsippany,UberEats,Abhishek S.,A120,Maghil,Abhishek chaki,A120,-6462484858,Low,Abhishek,chaki,Abhishek,S.
3,14d293a8-81c5-40b2-a208-be1c03a93fad,A2B Parsippany,UberEats,Abhishek S.,A120,Maghil,Abhishek,A120,-2012204715,Low,Abhishek,,Abhishek,S.
4,14d293a8-81c5-40b2-a208-be1c03a93fad,A2B Parsippany,UberEats,Abhishek S.,A120,Maghil,Abhishek,A120,-9734243785,Low,Abhishek,,Abhishek,S.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11758,7e2a8a81-1462-11eb-89a4-42010a010003,A2B SPF,UberEats,Venkat R.,V5236,Maghil,Venkat L,V5234,-6464310310,Low,Venkat,L,Venkat,R.
11759,7e2a8a81-1462-11eb-89a4-42010a010003,A2B SPF,UberEats,Venkat R.,V5236,Maghil,Venkata Munnangi,V52352,-7323227146,Low,Venkata,Munnangi,Venkat,R.
11760,7e2a8a81-1462-11eb-89a4-42010a010003,A2B SPF,UberEats,Venkat R.,V5236,Maghil,Venkatvenkat,V5231523,-7328619848,Low,Venkatvenkat,,Venkat,R.
11761,88cc107b-bc75-4d1a-9b35-9199e69d3b3d,A2B Warrenville,Uber eats,Bagya,B200,Maghil,Bagya,B200,-7327607938,High,Bagya,,Bagya,
11762,88cc107b-bc75-4d1a-9b35-9199e69d3b3d,A2B Warrenville,Uber eats,Bagya,B200,Maghil,Bagya,B200,-3127527095,High,Bagya,,Bagya,

In [4]:
import pandas as pd
from fuzzywuzzy import fuzz

data = pd.read_csv("./new.csv")

data['aggr_full_name'] = data['aggr_full_name'].str.lower()
data['full_name'] = data['full_name'].str.lower()
data['first_name'] = data['first_name'].str.lower()
data['last_name'] = data['last_name'].str.lower()
data['agg_first_name'] = data['agg_first_name'].str.lower()
data['agg_last_name'] = data['agg_last_name'].str.lower()

def calculate_similarity(row):
    return fuzz.ratio(str(row['aggr_full_name']), str(row['full_name']))

data['sim_sco_full_name'] = data.apply(calculate_similarity, axis=1)

def calculate_similarity_1(row):
    return fuzz.ratio(str(row['agg_first_name']), str(row['first_name']))

data['sim_sco_first_name'] = data.apply(calculate_similarity_1, axis=1)

def calculate_similarity_2(row):
    return fuzz.ratio(str(row['agg_last_name']), str(row['last_name']))

data['sim_sco_last_name'] = data.apply(calculate_similarity_2, axis=1)

data.to_csv("./new.csv",index=False)

C:\Users\subasini\AppData\Roaming\Python\Python311\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

In [5]:
data

,loc_id,loc_name,aggr_order_channel,aggr_full_name,aggr_soundex_score,channel,full_name,magil_soundex_score,maghil_phone,match_score,first_name,last_name,agg_first_name,agg_last_name,sim_sco_full_name,sim_sco_first_name,sim_sco_last_name
0,14d293a8-81c5-40b2-a208-be1c03a93fad,A2B Parsippany,UberEats,abhishek s.,A120,Maghil,abhishek,A120,-6292439194,Low,abhishek,NaN,abhishek,s.,84,100,0
1,14d293a8-81c5-40b2-a208-be1c03a93fad,A2B Parsippany,UberEats,abhishek s.,A120,Maghil,abhisek,A120,-9736416575,Low,abhisek,NaN,abhishek,s.,78,93,0
2,14d293a8-81c5-40b2-a208-be1c03a93fad,A2B Parsippany,UberEats,abhishek s.,A120,Maghil,abhishek chaki,A120,-6462484858,Low,abhishek,chaki,abhishek,s.,72,100,0
3,14d293a8-81c5-40b2-a208-be1c03a93fad,A2B Parsippany,UberEats,abhishek s.,A120,Maghil,abhishek,A120,-2012204715,Low,abhishek,NaN,abhishek,s.,84,100,0
4,14d293a8-81c5-40b2-a208-be1c03a93fad,A2B Parsippany,UberEats,abhishek s.,A120,Maghil,abhishek,A120,-9734243785,Low,abhishek,NaN,abhishek,s.,84,100,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11758,7e2a8a81-1462-11eb-89a4-42010a010003,A2B SPF,UberEats,venkat r.,V5236,Maghil,venkat l,V5234,-6464310310,Low,venkat,l,venkat,r.,82,100,0
11759,7e2a8a81-1462-11eb-89a4-42010a010003,A2B SPF,UberEats,venkat r.,V5236,Maghil,venkata munnangi,V52352,-7323227146,Low,venkata,munnangi,venkat,r.,56,92,0
11760,7e2a8a81-1462-11eb-89a4-42010a010003,A2B SPF,UberEats,venkat r.,V5236,Maghil,venkatvenkat,V5231523,-7328619848,Low,venkatvenkat,NaN,venkat,r.,57,67,0
11761,88cc107b-bc75-4d1a-9b35-9199e69d3b3d,A2B Warrenville,Uber eats,bagya,B200,Maghil,bagya,B200,-7327607938,High,bagya,NaN,bagya,NaN,91,100,100
11762,88cc107b-bc75-4d1a-9b35-9199e69d3b3d,A2B Warrenville,Uber eats,bagya,B200,Maghil,bagya,B200,-3127527095,High,bagya,NaN,bagya,NaN,100,100,100

In [6]:
import pandas as pd

df = pd.read_csv("./new.csv")

df_sorted = df.sort_values(by=['sim_sco_full_name'	,'sim_sco_first_name'	,'sim_sco_last_name'], ascending=[False, False,False])

df_sorted.to_csv("./new2.csv", index=False)

In [7]:
df_sorted

,loc_id,loc_name,aggr_order_channel,aggr_full_name,aggr_soundex_score,channel,full_name,magil_soundex_score,maghil_phone,match_score,first_name,last_name,agg_first_name,agg_last_name,sim_sco_full_name,sim_sco_first_name,sim_sco_last_name
591,22d293a8-81c5-40b2-a208-be1c03a93fad,A2B Princeton,Grubhub,ashish b,A210,Maghil,ashish b,A210,-9085100399,High,ashish,b,ashish,b,100,100,100
592,22d293a8-81c5-40b2-a208-be1c03a93fad,A2B Princeton,GrubHub,bhanu t,B530,Maghil,bhanu t,B530,-6097217531,High,bhanu,t,bhanu,t,100,100,100
593,22d293a8-81c5-40b2-a208-be1c03a93fad,A2B Princeton,Uber Eats,claire,C460,Maghil,claire,C460,-6263725343,High,claire,NaN,claire,NaN,100,100,100
594,22d293a8-81c5-40b2-a208-be1c03a93fad,A2B Princeton,DoorDash,guru,G600,Maghil,guru,G600,-4695362318,High,guru,NaN,guru,NaN,100,100,100
595,22d293a8-81c5-40b2-a208-be1c03a93fad,A2B Princeton,DoorDash,guru,G600,Maghil,guru,G600,-2017100500,High,guru,NaN,guru,NaN,100,100,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7707,22d293a8-81c5-40b2-a208-be1c03a93fad,A2B Princeton,Grubhub,venkat we ez t,V52323,Maghil,venkatakrishnan hariharan,V523262565,-6073721354,Low,venkatakrishnan,hariharan,venkat,we ez t,36,57,0
7188,22d293a8-81c5-40b2-a208-be1c03a93fad,A2B Princeton,UberEats,srinivasan m.,S65125,Maghil,srinu velichety,S651423,-7575810710,Low,srinu,velichety,srinivasan,m.,36,53,0
1873,22d293a8-81c5-40b2-a208-be1c03a93fad,A2B Princeton,UberEats,arun p.,A651,Maghil,arunvibooshanan,A65125,-4452061923,Low,arunvibooshanan,NaN,arun,p.,36,42,0
11592,7e2a8a81-1462-11eb-89a4-42010a010003,A2B SPF,UberEats,venkat r.,V5236,Maghil,venkiteswaran vaidyanathan,V52326513535,-2014232192,Low,venkiteswaran,vaidyanathan,venkat,r.,34,53,0
492,14d293a8-81c5-40b2-a208-be1c03a93fad,A2B Parsippany,UberEats,prashanth m.,P62535,Maghil,prasenjeet sengupta,P6252325213,-8478302292,Low,prasenjeet,sengupta,prashanth,m.,32,63,0